### ISSUE TITLE
lỗi không reset lại scroll 

### ISSUE THREAD

**Issue by htilssu** [htilssu/e-wallet-fe#40]
khi từ trang xem danh sách giao dịch nhấn vào  xem chi tiết scroll không được reset lại mà vẫn giữ nguyên -> muốn xem chi tiết phải lướt lên lại (#38 )

**Comment by Tuan980Blue** [comment]
đã fixxxxxxxx xonggggg

**Comment by htilssu** [comment]
gút chóp

**Comment by Tuan980Blue** [comment]
chuẩn bị review giúp mình OTP Verification
